#!/usr/bin/env python3

import sys
import subprocess

def main():
    # Read and print the first line (header)
    header = sys.stdin.readline().rstrip()
    print(header)

    # Apply the given command to the rest of the input
    if len(sys.argv) > 1:
        # Prepare the command to run
        command = sys.argv[1:]
        # Run the command with the rest of the stdin
        process = subprocess.Popen(command, stdin=subprocess.PIPE, text=True)

        for line in sys.stdin:
            process.stdin.write(line)

        process.stdin.close()
        process.wait()

if __name__ == "__main__":
    main()
