#!/usr/bin/env python3

import sys
import shutil
import argparse

def expand_tabs(input_lines, tabsize=8):
    """Expand tabs to spaces."""
    return [line.expandtabs(tabsize) for line in input_lines]

def trim_lines(input_lines, height, width):
    """Trim the input lines to the specified height and width."""
    output_lines = []
    for i, line in enumerate(input_lines):
        trimmed_line = line.rstrip()
        if width > 0 and len(trimmed_line) > width:
            trimmed_line = trimmed_line[:width - 1] + '…'
        output_lines.append(trimmed_line)
        if height > 0 and i + 1 >= height:
            break

    if height > 0 and len(input_lines) > height:
        remaining_lines = len(input_lines) - height
        if remaining_lines == 1:
            output_lines.append(input_lines[height].rstrip()[:width] + '…')
        elif remaining_lines > 1:
            output_lines.append(f'… with {remaining_lines} more lines')

    return output_lines

def main():
    parser = argparse.ArgumentParser(description="Trim output to a given height and width.")
    parser.add_argument('height', type=int, nargs='?', default=10, help="Number of lines to keep.")
    parser.add_argument('width', type=int, nargs='?', default=shutil.get_terminal_size().columns, help="Maximum width of each line.")
    args = parser.parse_args()

    input_lines = sys.stdin.readlines()
    expanded_lines = expand_tabs(input_lines)
    trimmed_output = trim_lines(expanded_lines, args.height, args.width)

    for line in trimmed_output:
        print(line)

if __name__ == "__main__":
    main()
